---
- hosts: test
  remote_user: root
  tasks:
     - name: rpm zabbix repo
       shell: rpm -ivh https://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm
       when:  ansible_distribution_major_version == "6"
       ignore_errors: yes
     - name: rpm zabbix repo
       shell: rpm -ivh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
       when:  ansible_distribution_major_version == "7"
       ignore_errors: yes
     - name: yum install agent
       yum: name=zabbix-agent state=present
     - name: modify conf
       shell: sed -i 's/Server=127.0.0.1/Server=192.168.8.194/g' /etc/zabbix/zabbix_agentd.conf
     - name: modify conf
       shell: sed -i 's/ServerActive=127.0.0.1/ServerActive=192.168.8.194/g' /etc/zabbix/zabbix_agentd.conf
     - name: modify conf
       shell: sed -i 's/Hostname=Zabbix server/Hostname={{ ansible_eth0.ipv4.address }}/g' /etc/zabbix/zabbix_agentd.conf
     - name: restart service
       service: name=zabbix-agent state=restarted enabled=yes